### ISSUE TITLE
create textmodel_cnnlstmemb

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda.classifiers#10]
The model that fits the embedding model, then the CNN/LSTM steps.

The function could have a logical argument to skip the CNN and/or embedding steps.

We will need to create a new utility function to convert the tokens into sequences for input into the cnn. (See https://github.com/quanteda/quanteda/issues/1145). So this will be:

```r
textmodel_cnnlstmemb.tokens(x, ...)
```

**Comment by pchest** [comment]
Hi Ken, I have submitted function called `tokens2sequences` that fits the parameters listed above.
